### PR TITLE
DOM_Query::get() no longer treats `0` index as `false'.

### PR DESCRIPTION
**Pull request by Ambient-Impact**
Hi there. I've been using this for a bit and it generally works quite well overall. I had some odd bugs where `DOM_Query::get()` was returning a node list instead of a specific node if the index passed was `0`, and I tracked it down to the overly broad if statement in Query.php, line 593:
```php
if ($index) {
```
This should be:
```php
if (is_int($index)) {
```
...or some other check that accounts for `0`.

### CODE REVIEW

**Comment by jslegers** [comment]
Thanks for your bugfix!

**Comment by Ambient-Impact** [comment]
No problem! Would you be interested in me contributing a few additional things? You can see I added a hasClass method as I found myself needing that, for example.

**Comment by jslegers** [comment]
> Would you be interested in me contributing a few additional things?

Sure. I haven't had much time to maintain this library recently, so I very much welcome your contributions.

> looks like my commit for hasClass got in as well, not sure if that was intentional. I'm pretty new to pull requests, so let me know if there's something I did wrong on my end. D:

A pull request is a request to merge one of your branches into the original branch in the original repo.

So, after you create a pull request from your repo to another repo, all subsequent commits you do from your local machine to your own repo are added to that pull request as long as they pull request hasn't been accepted.

It's kind of a pain, I know, and I can think of only two approaches to this :
* Either you create a separate branch for every set of changes you want to push, with one PR for every branch
* Either you create a PR for one set of changes, then wait until it's accepted, then create another PR, etc.

**Comment by Ambient-Impact** [comment]
Ah, that sorta makes sense. I'd been under the mistaken idea that a pull request was tied to a specific commit. Probably the best thing will be to create separate branches, in that case. Thanks!

**Pull request merged**
